FROM nvidia/cuda:12.1.1-runtime-ubuntu22.04

WORKDIR /app

COPY . /app
COPY weights /app/weights  

RUN apt-get update && apt-get install -y \
    python3 python3-pip libgl1-mesa-glx libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*

ENV PATH="/usr/local/cuda/bin:${PATH}"
ENV CUDA_HOME="/usr/local/cuda"

RUN pip install --no-cache-dir --upgrade pip setuptools wheel packaging
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]



